# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN dnf makecache && dnf --assumeyes install python3 sudo python3-devel python3-dnf bash && dnf clean all
