mariadb_versions:
  - "10.3"
  - "10.4"
  - "10.5"
  - "10.6"
  - "10.7"
  - "10.8"
  - "10.9"
  - "10.10"
  - "10.11"
  - "11.0"
mariadb_service: "mariadb"
percona_service: "mysql"
mysql_service: "mysql"
