---
- name: Authenticate
  block:
    - name: Get token
      retries: 3
      delay: 1
      until: auth_token.status == 200
      uri:
        url: "{{ rpc_url }}"
        method: POST
        body_format: json
        body:
          action: "{{ api_actions['auth'] }}"
          username: "{{ username }}"
          password: "{{ pin_rsa }}"
      register: auth_token
      failed_when: "false"
      check_mode: false

    - name: Fail if unable to obtain a token
      fail:
        msg: >
          Unable to retrieve a valid token,
          ({{ auth_token.json.error_message|default }})
          please retry or increase verbosity
      failed_when: >
        auth_token.status != 200 or
        auth_token.json.status_code != 200
      no_log: "false"

    - name: Set token
      set_fact:
        token: "{{ auth_token.json.authtoken }}"
      when: >
        auth_token.json.status_code == 200

    - name: Create cache file
      copy:
        content: "{{ token }}"
        dest: "{{ cache_file }}"
        mode: 0600
      when: token is defined

    - name: Suggest the use of cache playbook
      debug:
        msg: >
          NOTE: Cache file has been created in {{ cache_file }}. To avoid prompt
          for credentials, use the rax_ubuntu_repo.yml playbook.
      when: token is defined
      no_log: "false"
  delegate_to: localhost
  run_once: "yes"
  become: "no"
  no_log: "true"
...
