---
- name: Re/(Un)Install Nimbus
  become: "yes"
  hosts: all
  pre_tasks:
  - name: Get CORE data when using ACE
    include_tasks: ace.yml
    when: config_id is defined
  tasks:
  - include_role:
      name: nimbus
...
