# Update local user password
# Tested with Ansible 2.3.1.0

- hosts: all
  become: True
  gather_facts: False

  vars_prompt:
    - name: username
      prompt: "Username"
      private: no

  tasks:
  - include_role:
      name: password_update
...
