---
- name: Patching(RHN/Spacewalk) registration (cache)
  become: "yes"
  hosts: all
  gather_facts: "yes"
  vars_prompt:
    - name: username
      prompt: username(SSO)
      private: "no"
    - name: pin_rsa
      prompt: PIN+RSA
      private: "yes"
  tasks:
  - name: Red Hat based distros
    include_role:
      name: rhn
    vars:
      authenticate: "yes"
    when: >
      ( ansible_os_family|lower in ['redhat'] and
        ansible_distribution_major_version in ['6', '7'] )

  - name: Ubuntu distros
    include_role:
      name: rax_ubuntu_repo
    vars:
      authenticate: "yes"
    when: >
      ( ansible_distribution|lower in ['ubuntu'] and
        ansible_distribution_version in ['14.04', '16.04'] )
...
