---
- name: Create Rackspace cookies
  become: "yes"
  hosts: all
  gather_facts: "False"
  pre_tasks:
  - name: Get CORE data when using ACE
    include_tasks: ace.yml
    when: config_id is defined
  tasks:
  - include_role:
      name: rscookies_create
...
