---
- hosts: all
  become: true

  vars_prompt:
    # Typical answer is 'customeremaildomain.com'
    - name: DOMAIN
      prompt: "Customers domain or subdomain"
      private: false

    # Typical answer is all caps WORKGROUP (ie. the AD domain name w/o the suf)
    - name: WORKGROUP
      prompt: >-
        Customers Workgroup: (press enter for magic default of the above
        variable up to the first .)
      default: 'magic'
      private: false

    # I had to use user@WORKGROUP.COM to be sucessful
    - name: JOINACCT
      prompt: >-
        Username for domain join
        (domain from above will be appended if no '@' is present)
      private: false

    # CASE SENSITIVE
    - name: JOINPWD
      prompt: "Password for domain join"
      private: true

    # These are the DNS Servers for the customer domain (The domain controllers)
    - name: DNSSERVERS
      prompt: Enter the IPs of the DNS server(s), comma separated
      private: false

    # Some customers may want to configure sssd enumeration but we will
    # disable it by default
    # ref: https://docs.pagure.org/SSSD.sssd/users/faq.html#when-should-i-enable-enumeration-in-sssd-or-why-is-enumeration-disabled-by-default
    - name: ENUMERATE
      prompt: Configure sssd enumeration y/N?
      default: 'n'
      private: false

    # By default, we won't update any config if this device is already
    # domain joined but allow this to be overridden
    - name: JOINAGAIN
      prompt: "Continue if device is already domain joined? y/N"
      default: "n"
      private: false

    # In some cases, customers may not want all known users to be
    # permitted to log into all devices.  For now this is done by
    # group only in the playbook, better to manage per-user access by
    # changing group membership in a central location than individual
    # user access on many sssd clients
    - name: ALLOW_GROUPS
      prompt: >-
        If applicable, enter AD groups whitelisted for login, comma separated,
        or leave blank if not
      default: 'n'
      private: false

  vars:
    type: customer
  tasks:
    - include_role:
        name: sssd_ad
...
