---

- hosts: RHEL
  become: true
  tasks:

  - name: Install on EL7
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: Install on EL8
    dnf:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- hosts: Debian
  become: true
  tasks:

  - name: Install apache package on ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "22" 
