---
- name: Look for local copy of the installer
  become: "no"
  run_once: "yes"
  local_action:
    module: stat
    path: "{{ al_pkg_file }}"
  register: local_installer

# Fetch the installer only when it does not exist locally or when is stale
# for 3 days.
- name: Fetch the installer
  become: "no"
  run_once: "yes"
  local_action:
    module: get_url
    url: "{{ al_url }}{{ al_pkg }}"
    dest: "{{ al_pkg_file }}"
  when: >-
    ( not local_installer.stat.exists or
      ( '%j' | strftime(ansible_date_time.epoch) | int -
        '%j' | strftime(local_installer.stat.ctime) | int
      ) | abs > 3
    )

- name: Push installer
  copy:
    src: "{{ al_pkg_file }}"
    dest: "{{ al_pkg_file }}"
...
