---
- name: Check if syslog config file exists
  stat:
    path: "{{ syslog_conf.file }}"
  register: syslog_exists

- name: Config rsyslog to log to alertlogic agent
  lineinfile:
    dest: "{{ syslog_conf.file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: "yes"
  with_items: "{{ syslog_conf.lines }}"
  notify: restart {{ syslog_daemon }}
  when: >
    syslog_exists.stat.exists and
    al_is_validated is defined
...
