---
# RHEL/CentOS 5 -> ManagedProbes | Intensiveprobes
- name: Define nimbus package for Red Hat-based distros version 5
  set_fact:
    nimbus_package: "\
      {{ rs_target_sla }}\
      {{ 'Probes' if rs_target_sla == 'Managed' else 'probes' }}"
  changed_when: "False"

...
