---
- name: restart apache
  service:
      name: "{{ apache_srv }}"
      state: restarted
  ignore_errors: yes

- name: restart php-fpm
  service:
      name: "{{ php_fpm_srv }}"
      state: restarted
  ignore_errors: yes

- name: restart php7-fpm
  service:
      name: php7.0-fpm
      state: restarted
  ignore_errors: yes
