---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

lint: |
  yamllint .

platforms:
  - name: molecule_sophos_c6
    image: ${DOCKER_REPO:-docker.artifacts.rackspace.net}/centos:6
    privileged: true
    network_mode: ${DOCKER_NETWORK_MODE:-bridge}

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_LIBRARY: ../../../../library
    ANSIBLE_MODULE_UTILS: ../../../../module_utils
    ANSIBLE_ROLES_PATH: ../../../../roles
  playbooks:
    converge: ../resources/converge.yml
    cleanup: ../resources/cleanup.yml
    prepare: ../resources/prepare.yml
    verify: ../resources/verify_install.yml
  inventory:
    group_vars:
      all:
        use_installer_pkg: ${USE_INSTALLER_PKG:-1}

scenario:
  test_sequence:
    - syntax
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
...
