---
rs_ctkapi_info:
  account_manager: Ginger Lee
  account_name: Linux Support Test Account
  account_num: '27329'
  account_service_level: Managed
  admin_pass: TZafbJEJeS2Z
  admin_user: root
  bdc: Ginger Lee
  behind: []
  datacenter: ORD1
  dmgs: "Device owner: Ryan Stark\r\nDevice owner Desk Phone: 506-1112\r\nDevice\
    \ owner Cell Phone: 210-859-9477\r\nDevice owner Email: starkindustries@rackspace.com\r\
    \nDevice owner Manager: Keith Ross\r\nDevice owner Manager Email: keith.ross@rackspace.com\r\
    \nDevice owner Department: Engine Room Linux Support\r\n\r\nSECURITY / APPROVALS\
    \ / PERMISSIONS / CHANGE CONTROL (DEVICE LEVEL)\r\n\r\n============================\r\
    \n\r\n(Any specific compliance codes they are meeting (PCI, HIPPA, etc))\r\
    \n\r\n(Tasks requiring specific approvals)\r\n\r\n============================\r\
    \n\r\nLOGIN CONSIDERATION / NOTES (DEVICE LEVEL)\r\n\r\n============================\r\
    \n\r\n(Special login considerations/notes)\r\n\r\n============================\r\
    \n\r\nSPECIAL NOTES (DEVICE LEVEL)\r\n\r\n============================\r\
    \n\r\n(Relevant device level notes)\r\n\r\n============================\r\
    \n\r\nDEVICE FUNCTION (DEVICE LEVEL)\r\n\r\n============================\r\
    \n\r\n(Relevant device description)\r\n\r\n============================\r\
    \n\r\nDevice Management Guidelines updated by Ryan Stark on 2016/08/17"
  drac: null
  drac_gateway: null
  drac_pass: []
  drac_user: []
  drac_vlan: null
  failover_device: null
  gateway: 184.106.28.249
  has_managed_backup: true
  icon_path: https://28616ea5aab979dce92c-69a5bc1f8c3c585c4f658970ef961bb7.ssl.cf2.rackcdn.com/vmlinux.gif
  in_front:
    - 860007
    - 859998
  ip_addresses:
    - 10.132.254.197
    - 184.106.28.250
  is_cluster: false
  lead_tech: null
  login_method: Password Auth
  nat_comments: []
  netmask: 255.255.255.248
  nickname: 300001-cent6
  online_date: '2015-10-28 10:58:32'
  os_type: Linux
  os_version: CentOS 6
  platform_model: Virtual Machine Linux
  platform_name: Virtual Machine Linux
  port: []
  primary_ip: 184.106.28.250
  primary_userid: rstark
  primary_userid_password: l7KI63DRiMPf
  private_gateway: 172.24.16.1
  private_ip: 172.24.16.250
  private_netmask: 255.255.252.0
  protocol: []
  rack_password: bHNf9GG7ZG0a
  rba_login_user: ''
  rba_login_user_password: ''
  root_method: sudo
  root_method_id:
    attributes: https://ws.core.rackspace.com/ctkapi/attributes/Computer.ComputerRootAccess
    class_name: Computer.ComputerRootAccess
    class_type: Value_Table
    description: sudo
    id: 2
    load_value: id
    methods: https://ws.core.rackspace.com/ctkapi/methods/Computer.ComputerRootAccess
    name: sudo
    values: https://ws.core.rackspace.com/ctkapi/values/Computer.ComputerRootAccess
  segment: ENT Z
  server: 300001
  server_name: 300001-cent6.rackersupport.com
  service_level_name: Intensive
  service_levels:
    attribute: service_products
    subattributes:
      - label: OS Management
        value: Customer  Managed
      - label: Hardware Management
        value: Rackspace  Managed
      - label: DC Level
        value: Rackspace Standard
      - label: Application Management
        value: Customer    Managed
  servicenet_ips:
    - 10.132.254.197
  servicenet_vlan_ids:
    - 2838
  ssh_key_passphrase: ''
  ssh_key_private: ''
  status: Rekick
  status_id: 51
  team: ENTZ-7MIX
rs_customer: '27329'
rs_datacenter: ORD1
rs_device_id: '300001'
rs_device_name: 300001-cent6.rackersupport.com
rs_target_sla: Intensive
rs_obm_ip: null
rs_obm_pass: null
rs_obm_user: null
rs_ohthree_info: null
rs_os_sku: CentOS 6
rs_platform: Virtual Machine
rs_platform_vendor: VMWare
rs_public_cloud_info: null
rs_region: ORD
rs_server: '300001'
rs_server_type: core
...
