---

- name: Create temp file for configuring ilo
  tempfile:
    state: file
  changed_when: false
  register: tmp_ilo_xml_config

- block:
    - name: Populate password settings in temp file
      template:
        dest: "{{ tmp_ilo_xml_config.path }}"
        src: ../templates/ilo-pw-reset.xml.j2
        owner: root
        group: root
        mode: 0600
      changed_when: false

    - name: Reset ilo password
      shell: /sbin/hponcfg -f {{ tmp_ilo_xml_config.path }}

  always:
    - name: Delete temp file for configuring ilo
      file:
        path: "{{ tmp_ilo_xml_config.path }}"
        state: absent
      changed_when: false