---
# Tasks for RedHat-based OSes
- name: List current repos
  ansible.builtin.command:
    cmd: "{{ yum_config_mgr_cmd[ansible_distribution_major_version | int] }}"
  register: repo_list
  changed_when: false

- name: Install rackspace-rax repo
  ansible.builtin.package:
    name: "{{ rax_mirror_base }}/release/{{ rax_release_rpm }}"
    state: present
    disable_gpg_check: true
  when:
    - not 'rax-release-rackspace' in packages
    - not repo_list is
        search('baseurl\s*=\s*https:\/\/rax\.mirror\.rackspace\.com\/el')

- name: Install epel repo
  ansible.builtin.package:
    name: epel-release-rackspace
  when:
    - not 'epel-release-rackspace' in packages
    - not 'epel-release' in packages
    - not repo_list is search('epel')

- name: Update packages to install for holland-py3 on EL7
  ansible.builtin.set_fact:
    install_packages:
      - rs-holland-py3-cohesity
  when: el7_py3 is defined
