---
- include_tasks: preflight.yml

- name: gather facts
  setup:

- include_tasks: osverification.yml

- name: Redhat Migration
  include: redhat/main.yml
  when: ansible_distribution == 'RedHat'

- name: CentOS Migration
  include: centos/main.yml
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'

- name: Oracle Migration
  include: oracle/main.yml
  when:
    - ansible_distribution == 'OracleLinux'
    - ansible_distribution_major_version in ('7','8')

- include_tasks: postflight.yml
