---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
  - name: Install EPEL repo on el6
    yum:
      name: epel-release
      state: present
      update_cache: true
    when:
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version|int == 6

  - name: Install deb dependencies
    apt:
      name:
        - python-apt
        - python3-apt
      state: present
      update_cache: true
    when: ansible_os_family == "Debian"
...
