---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  # Ansible 2.8.6 is required due to a bug in package_facts for apt
  - name: Get packages
    package_facts:
      manager: auto

  - name: Get services
    service_facts:

  - name: Get service name
    set_fact:
      svc_name: "{%- if ansible_distribution_major_version|int == 6 -%}
      vmtoolsd
      {%- elif ansible_os_family == 'Debian' -%}
      open-vm-tools.service
      {%- else -%}
      vmtoolsd.service
      {%- endif -%}"

  - name: Verify package is installed
    assert:
      that: ("open-vm-tools" in packages)

  # The open-vm-tools daemon will stop because it requires to detect vmware
  # guest it will be stopped with: "ConditionVirtualization=vmware was not met"
  - name: Verify service is enabled
    assert:
      that:
        - services[svc_name].status == "enabled"
...
