---
- name: Verify upgrade completed successfully
  hosts: all
  gather_facts: false
  gather_subset:
    - min
  tasks:
    - name: Collect package facts
      package_facts:
        manager: auto

    - name: Collect service facts
      service_facts:

    - name: Verify PHP packages are installed
      assert:
        that: packages["mod_php74"] is defined
...
