- name: Verify OS is RHEL 6, 7, or 8
  assert:
    that:
      - ansible_distribution == 'RedHat'
      - ansible_distribution_major_version in ('6', '7', '8')

- block:
    - name: Check network connection
      wait_for:
        host: rhui.rackspace.com
        port: 443
        timeout: 5

  rescue:
    - name: Report RHUI connection error to Rigatoni
      delegate_to: localhost
      become: false
      uri:
        url: "https://stepladder.rax.io/api/rigatoni/v1/reports/GTSENG-205/{{ device_id }}"
        method: POST
        return_content: true
        headers:
          accept: application/json
          X-Auth-Token: "{{ rackertoken }}"
        body: "{\"result_code\":\"16\"}"
        body_format: json
      when: rigatoni

    - name: Fail on Unsupported OS
      fail:
        msg: "Could not connect to RHUI infrastructure"
