- name: Populate service facts
  ansible.builtin.service_facts:

- name: Stop RHN services
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - rhnsd
    - osad
  when: item in ansible_facts.services

- name: Remove rhn oriented packages
  yum:
    name:
      - rhnsd
      - osad
      - yum-rhn-plugin
      - osa-common
      - spacewalk-backend-usix
      - rhn-setup
      - rhn-client-tools
      - rhn-check
      - rhnlib
      - rhncfg-client
      - rhncfg-actions
      - rhncfg
      - rhn-org-trusted-ssl-cert
      - rs-release
      - rs-epel-release
    state: absent
  register: rhn_uninstall
  failed_when: rhn_uninstall.rc|int not in [0,1]

- name: Remove stale yum data
  file:
    state: absent
    path:
      - /etc/yum/pluginconf.d/rhnplugin.conf.rpmsave
      - /etc/sysconfig/rhn/up2date.rpmsave
      - /etc/sysconfig/rhn/osad-auth.conf.rpmsave

- name: Remove stale yum cache
  file:
    state: absent
    path: /var/cache/yum
