---
- name: Prepare
  hosts: all
  gather_facts: true
  gather_subset: min
  tasks:
    - name: Install ntp
      package:
        name: ntp

    - name: Start and enable ntp service
      vars:
        ntp_service_name:
          RedHat: ntpd
          Debian: ntp
      service:
        name: "{{ ntp_service_name[ansible_os_family] }}"
        enabled: true
        state: started
...
