## Source: https://gist.github.com/BlackDex/838fb220b5f6231b35637498cfecb2eb


{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

ENV container docker
ENV LC_ALL=C TZ=UTC TERM=xterm-256color

RUN export DEBIAN_FRONTEND=noninteractive ; \
      export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 ; \
      apt update \
      && apt install -y dbus systemd gnupg systemd-sysv python3 sudo bash ca-certificates iproute2 python3-apt aptitude \
      && apt clean \
      && rm -rf /usr/share/doc/* /usr/share/man/* /var/lib/apt/lists/* /tmp/* /var/tmp/*; \

# Don't start any optional services except for the few we need.
# Ignore any errors since some directories could not exists on some distributions
RUN find /etc/systemd/system \
      /lib/systemd/system \
      /usr/lib/systemd/system \
      -path '*.wants/*' \
      -not -name '*dbus*' \
      -not -name '*journald*' \
      -not -name '*systemd-tmpfiles*' \
      -not -name '*systemd-user-sessions*' \
      -exec rm \{} \; ; >/dev/null 2>&1

# If image does have systemd set the default to be multi-user else leave it as is.
RUN if [ $(command -v systemctl) ]; then \
      systemctl set-default multi-user.target; \
    fi

RUN printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d

STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init"]
