---
- name: Backup existing my.cnf
  command: cp -aL "{{ my_cnf }}" /home/rack/{{ ticket_no }}/my.cnf.{{ ansible_date_time.date }}
  args:
    creates: /home/rack/{{ ticket_no }}/my.cnf.{{ ansible_date_time.date }}
  tags: upgrade_mycnf

- name: Upgrade 5.1 to 5.5
  shell: >
    {{ discovered_interpreter_python }} /home/rack/{{ ticket_no }}/upgrade_mysql_config.py
    --config "{{ my_cnf }}"
    --target 5.5 > /home/rack/{{ ticket_no }}/ansible_my.cnf55
  when: mysql.version.full.startswith("5.1")
  tags: upgrade_mycnf

- name: Upgrade 5.5 to 5.6
  shell: >
    {{ discovered_interpreter_python }} /home/rack/{{ ticket_no }}/upgrade_mysql_config.py
    --config "{{ my_cnf }}"
    --target 5.6 > /home/rack/{{ ticket_no }}/ansible_my.cnf56
  when: mysql.version.full.startswith("5.5")
  tags: upgrade_mycnf

- name: Upgrade 5.6 to 5.7
  shell: >
    {{ discovered_interpreter_python }} /home/rack/{{ ticket_no }}/upgrade_mysql_config.py
    --config "{{ my_cnf }}"
    --target 5.7 > /home/rack/{{ ticket_no }}/ansible_my.cnf57
  when: mysql.version.full.startswith("5.6")
  tags: upgrade_mycnf

- name: Upgrade 5.7 to 8.0
  shell: >
    {{ discovered_interpreter_python }} /home/rack/{{ ticket_no }}/upgrade_mysql_config.py
    --config "{{ my_cnf }}"
    --target 8.0 > /home/rack/{{ ticket_no }}/ansible_my.cnf80
  when: mysql.version.full.startswith("5.7")
  tags: upgrade_mycnf
